#!/bin/bash

# Función para enviar texto a un campo de entrada
send_text() {
    input text "$1"
}

# Abre la aplicación Google Chrome
am start -n com.android.chrome/com.google.android.apps.chrome.Main -d "https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fwww.google.com%2F&ec=GAZAmgQ&hl=es&ifkv=ATuJsjyPXIDBWpYk9SjuNgFvKMLBYCYlJiH6bonTyPGTBVLBwO9KoQx87zl40dpFcICimtVbtD_LVw&passive=true&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S-553091199%3A1708212033812302&theme=glif"

# Espera unos segundos para que la aplicación se abra completamente (ajustar según sea necesario)
sleep 5

# Envía el texto "pepe123" al campo de entrada
send_text "pepe123"
